language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

branches:
  except:
    - example-data
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: change

