language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

branches:
  except:
    - example-data
    - gh-pages

apt_packages: 
    - build-essential
    - tcl
    - tk

notifications:
  email:
    on_success: change
    on_failure: change

