language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

before_install:
  - tlmgr install index

branches:
  except:
    - example-data
    - gh-pages

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

r_packages:
    - sm
    - vioplot

notifications:
  email:
    on_success: change
    on_failure: change

