language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

before_install:
  - tlmgr install index

branches:
  except:
    - example-data
    - gh-pages

apt_packages: 
    - build-essential
    - tcl8.6
    - tk8.6
    - tcl8.6-dev
    - tk8.6-dev

r_packages:
    - sm
    - vioplot

notifications:
  email:
    on_success: change
    on_failure: change

